// components/profile/ProfileFooter/index.vue
<script setup lang="ts">
defineProps<{
  name: string;
  isRetro: boolean;
}>();

const currentYear = new Date().getFullYear();
</script>

<template>
  <footer class="text-center mt-auto px-4 z-10 relative">
    <p 
      :class="[
        'text-[11px] uppercase tracking-widest opacity-60',
        isRetro ? 'font-mono text-black font-bold' : 'font-sans text-[var(--text-body)]'
      ]"
    >
      &copy; {{ currentYear }} RAFIESTER &bull; PERSONAL SPACE
    </p>
  </footer>
</template>

// src/components/profile/ProfileFooter.tsx
import React from 'react';

interface ProfileFooterProps {
  name: string;
  isRetro: boolean;
}

export default function ProfileFooter({ name, isRetro }: ProfileFooterProps) {
  return (
    <footer className="text-center mt-auto px-4 z-10 relative">
      <p 
        className={`
          text-[11px] uppercase tracking-widest opacity-60
          ${isRetro ? 'font-mono text-black font-bold' : 'font-sans text-[var(--text-body)]'}
        `}
      >
        &copy; {new Date().getFullYear()} {name} &bull; Supabase CMS Integration
      </p>
    </footer>
  );
}
