// components/admin/DashboardHeader/index.vue
<template>
  <header className="border-b border-white/[0.04] bg-[#1a1a24]/80 backdrop-blur-xl sticky top-0 z-40">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
      <!-- Left: Brand -->
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2.5">
          <div className="leading-none">
            <h1 className="text-sm font-semibold text-white/85 tracking-tight">Muffytreen CMS</h1>
          </div>
        </div>
      </div>

      <!-- Right Section is now empty -->
      <div className="flex items-center gap-2" />
    </div>
  </header>
</template>

// src/components/admin/DashboardHeader.tsx
import React from 'react';

export default function DashboardHeader() {
  return (
    <header className="border-b border-white/[0.04] bg-[#1a1a24]/80 backdrop-blur-xl sticky top-0 z-40">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
        {/* Left: Brand */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2.5">
            <div className="leading-none">
              <h1 className="text-sm font-semibold text-white/85 tracking-tight">Muffytreen CMS</h1>
            </div>
          </div>
        </div>

        {/* Right Section is now empty */}
        <div className="flex items-center gap-2" />
      </div>
    </header>
  );
}
